name: bilibili_live_danmu_proxy
description: Bilibili Live API HTTP proxy server command-line application.
version: 1.0.0
repository: https://github.com/AoEiuV020/flutter_bilibili_live_danmu
publish_to: none

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  bilibili_live_api_server:
    path: ../../packages/bilibili_live_api_server
  args: ^2.6.0
  logger: ^2.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
